package symPackage;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class RuSymbicortImpl extends EntityImpl 
{
  public static final int CHAIN = 0;
  public static final int STORENBR = 1;
  public static final int PRESCNBR = 2;
  public static final int TRANSNBR = 3;
  public static final int TRANSDATE = 4;
  public static final int MOLECULE = 5;
  public static final int ROWID = 6;

  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public RuSymbicortImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("symPackage.RuSymbicort");
    }
    return mDefinitionObject;
  }


  /**
   * 
   *  Gets the attribute value for Chain, using the alias name Chain
   */
  public String getChain()
  {
    return (String)getAttributeInternal(CHAIN);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Chain
   */
  public void setChain(String value)
  {
    setAttributeInternal(CHAIN, value);
  }

  /**
   * 
   *  Gets the attribute value for StoreNbr, using the alias name StoreNbr
   */
  public String getStoreNbr()
  {
    return (String)getAttributeInternal(STORENBR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for StoreNbr
   */
  public void setStoreNbr(String value)
  {
    setAttributeInternal(STORENBR, value);
  }

  /**
   * 
   *  Gets the attribute value for PrescNbr, using the alias name PrescNbr
   */
  public String getPrescNbr()
  {
    return (String)getAttributeInternal(PRESCNBR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for PrescNbr
   */
  public void setPrescNbr(String value)
  {
    setAttributeInternal(PRESCNBR, value);
  }

  /**
   * 
   *  Gets the attribute value for TransNbr, using the alias name TransNbr
   */
  public String getTransNbr()
  {
    return (String)getAttributeInternal(TRANSNBR);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for TransNbr
   */
  public void setTransNbr(String value)
  {
    setAttributeInternal(TRANSNBR, value);
  }

  /**
   * 
   *  Gets the attribute value for TransDate, using the alias name TransDate
   */
  public Date getTransDate()
  {
    return (Date)getAttributeInternal(TRANSDATE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for TransDate
   */
  public void setTransDate(Date value)
  {
    setAttributeInternal(TRANSDATE, value);
  }

  /**
   * 
   *  Gets the attribute value for Molecule, using the alias name Molecule
   */
  public String getMolecule()
  {
    return (String)getAttributeInternal(MOLECULE);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for Molecule
   */
  public void setMolecule(String value)
  {
    setAttributeInternal(MOLECULE, value);
  }

  /**
   * 
   *  Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }

  /**
   * 
   *  getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CHAIN:
        return getChain();
      case STORENBR:
        return getStoreNbr();
      case PRESCNBR:
        return getPrescNbr();
      case TRANSNBR:
        return getTransNbr();
      case TRANSDATE:
        return getTransDate();
      case MOLECULE:
        return getMolecule();
      case ROWID:
        return getRowID();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }

  /**
   * 
   *  setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CHAIN:
        setChain((String)value);
        return;
      case STORENBR:
        setStoreNbr((String)value);
        return;
      case PRESCNBR:
        setPrescNbr((String)value);
        return;
      case TRANSNBR:
        setTransNbr((String)value);
        return;
      case TRANSDATE:
        setTransDate((Date)value);
        return;
      case MOLECULE:
        setMolecule((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}