package symPackage;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class symmoduleImpl extends ApplicationModuleImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public symmoduleImpl()
  {
  }

  /**
   * 
   *  Container's getter for RuSymbicortView1
   */
  public RuSymbicortViewImpl getRuSymbicortView1()
  {
    return (RuSymbicortViewImpl)findViewObject("RuSymbicortView1");
  }

  /**
   * 
   *  Container's getter for RuSymbicortView1_1
   */
  public RuSymbicortView1Impl getRuSymbicortView1_1()
  {
    return (RuSymbicortView1Impl)findViewObject("RuSymbicortView1_1");
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("symPackage", "symmoduleLocal");
  }
}