package mypackage1;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AppModuleImpl extends ApplicationModuleImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AppModuleImpl()
  {
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("mypackage1", "AppModuleLocal");
  }
}